site_name: Workshops Documentation
site_url: https://rhysjj111.github.io/workshop-docs/
nav:
  # - Home: index.md
  # - Workshop Coordinator:
  #   - Overview: coordinator/coord-overview.md
  #   - Components: coordinator/coord-components.md
  - Techman Software:
    # - Overview: techman/tech-overview.md
    - Quick guide: techman/core.md
    # - Elements:
    #   - Jobcards: techman/components/jobcard.md
    #   - Jobcards:
    #     - Create a Job: techman/components/jobcards/create-job.md
    #     - Products: techman/components/jobcards/products.md
    #     - Process an Invoice: techman/components/jobcards/send-invoice.md
    #   - Purchase orders: techman/components/purchase-orders.md
    #   - Returns: techman/components/returns.md
    #   - Estimates: techman/components/estimates.md
    #   - Customers: techman/components/customers.md
    #   - Vehicles: techman/components/vehicles.md

theme:
  icon:
    admonition:
      tip: octicons/video-16
      example: material/camera
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  language: en
  # palette:
  #   - scheme: default
      # toggle:
      #   icon: material/toggle-switch-off-outline
      #   name: Switch to dark mode
      # accent: amber
      # primary: blue
    # - scheme: slate
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
    #   accent: amber
    #   primary: lime

# plugins:
#   - social
#   - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      # link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      # link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      # link: https://www.linkedin.com/in/willettjames/
    

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# copyright: |
#   &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>